include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    lines_longer_than_80_chars: false
    flutter_style_todos: false
    public_member_api_docs: false
    cascade_invocations: false
    omit_local_variable_types: false
