name: flutter_app_info
description: Utility package to easily access device, platform, target, package, and app version information
version: 2.0.0
maintainer: Taza Technology LLC
repository: https://github.com/tazatechnology/flutter_app_info
issue_tracker: https://github.com/tazatechnology/flutter_app_info/issues
homepage: https://tazatechnology.com
documentation: https://github.com/tazatechnology/flutter_app_info

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  device_info_plus: ^9.1.1
  package_info_plus: ^5.0.1
  version: ^3.0.2
  universal_io: ^2.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  