name: flutter_app_info
description: Utility package to easily access device, platform, target, package, and app version information
version: 3.0.3
maintainer: Taza Technology LLC
repository: https://github.com/tazatechnology/flutter_app_info
issue_tracker: https://github.com/tazatechnology/flutter_app_info/issues
homepage: https://tazatechnology.com
documentation: https://github.com/tazatechnology/flutter_app_info

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  device_info_plus: ^11.0.0
  flutter:
    sdk: flutter
  package_info_plus: ^8.0.0
  universal_io: ^2.2.0
  version: ^3.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
  