# Continuous Deployment: Publish Package to pub.dev
name: CD Publish

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    permissions:
      id-token: 'write'